
export const ActionTypes = {
    GET_NATION_STATS: "GET_NATION_STATS",
    GET_STATE_STATS: "GET_STATE_STATS",
    GET_SINGLE_STATE_STATS: "GET_SINGLE_STATE_STATS",

    TOGGLE_DATAPOINT: "TOGGLE_DATAPOINT",
    TOGGLE_OPEN_FILTER: "TOGGLE_OPEN_FILTER",

    TOGGLE_MAP_DATAPOINT: "TOGGLE_MAP_DATAPOINT",

    SET_MAP_ACTIVE_STATE: "SET_MAP_ACTIVE_STATE"
}

export const AsyncActionPostfix = {
    ASYNC_IN_PROGRESS: "_ASYNC_IN_PROGRESS",
    ASYNC_SUCCESS: "_ASYNC_SUCCESS",
    ASYNC_FAILURE: "_ASYNC_FAILURE"
}